services:
  db:
    image: mariadb:10.11
    container_name: db
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD:-asdf1234}
      MARIADB_DATABASE: ${MARIADB_DATABASE:-tweetchat}
    volumes:
      - mariadb_data:/var/lib/mysql
    ports:
      - "3306:3306"

  tweetchat-backend:
    build: ./tweetchat-backend
    container_name: tweetchat-backend
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://db:3306/tweetchat
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: ${MARIADB_ROOT_PASSWORD:-asdf1234}
      APP_JWT_SECRET: ${APP_JWT_SECRET:-YourSuperSecretKeyForJWTGenerationAndValidationMustBeLongAndComplexEnoughForHS256}
    volumes:
      - backend_uploads:/app/uploads

  tweetchat-frontend:
    build: ./tweetchat-frontend
    container_name: tweetchat-frontend
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - tweetchat-backend
    environment:

      - VITE_API_URL=http://localhost:8080/api

volumes:
  mariadb_data:
  backend_uploads: